module.exports = {"personality": {
	"allornone" : "Your can often find it challenging to stick to a particular diet or exercise plan because of difficulties with planning ahead.\n\nWhile you may initially feel motivated to start working towards your healthy lifestyle goals, it can be hard to stay on track without structure, which means minor setbacks— like one day of bad eating— can derail you completely.\n\nLike a trusted friend, your certified coach will help you add structure to your day and keep you motivated and accountable to work towards your goals— one small step at a time.",
	"opportunity" : "Because your pace and lifestyle is fast, it’s common for you to eat faster than everyone else at the table, making it easy to go back for seconds or even thirds. This can lead to you feeling unconscious and disconnected from true hunger.\n\nEating when you are not hungry often leads to excess snacking and over eating.\n\nLike a trusted friend, your certified coach will support you and help you get in touch with your true hunger and show you how to eat mindfully.",
	"emotion" : "Whether you are feeling positive or negative emotions, you may turn to food for comfort, as a means of distraction or even celebration.\n\nDuring these emotional times, you may find yourself reaching for foods that are high in fat or sugar. These foods can make you feel better immediately, but the feeling doesn’t last. Instead you are left to deal with the original trigger and feelings of guilt due to over indulging.\n\nLike a trusted friend, your certified coach will support you and help you manage stress and work on problem solving techniques."
  }
, "nutrition": {
	"standard" : "Your certified health coach will help you plan meals and snacks to support your standard diet, and ensure you are receiving adequate amounts of calories and nutrients. You can enjoy a variety of food and treats that are healthy and delicious.",
	"vegetarian" : "Your certified health coach will help you plan meals and snacks to support your vegetarian diet, and ensure you are receiving adequate amounts of calories and nutrients. You can enjoy a variety of food and treats that are healthy and delicious.",
	 "vegan" : "Your certified health coach will help you plan meals and snacks to support your vegan diet, and ensure you are receiving adequate amounts of calories and nutrients. You can enjoy a variety of food and treats that are healthy and delicious."
  }
, "wellbeing": {
	"mood" : "When your mood is low, you may be feeling more down than usual, which makes it harder to to take care of daily tasks, let alone working towards your healthier lifestyle goals.\n\nYou will benefit from the ongoing guidance and support of your certified personal coach who will help you use exercise to improve your mood.\n\nThat being said, if your mood continues to drop and you feel other distressing symptoms such as loss of interest, changes in appetite, sleep disruptions or feelings of hopelessness you should consult your medical doctor.",
	"anxiety" : "With high anxiety levels, you will feel tense, which can affect your muscles, your breathing, and your heart rate. You might also feel light-headed and mentally preoccupied.\n\nYou will benefit from the ongoing guidance and support of your certified personal coach who will help you manage your anxiety with exercise, and relaxation techniques. This will help your overall well-being and improve your coping abilities.\n\nThat being said, if your anxiety continues to rise you should consult your medical doctor.",
	"sleep" : "With poor sleeping habits, the chances are you are not getting a good quality sleep, or sleeping the required 7 – 9 hours a night.\n\nSleep deprivation impacts more than just energy levels. Sleep deprivation also influences your weight, causes food cravings, hormonal imbalances and prevents the burning of calories during REM sleep.\n\nYou will benefit from the ongoing guidance and support of your certified personal coach who will help you practice good sleep habits to improve your sleep quality.",
	"energy" : "Our energy levels are influenced by the combination and quantity of foods we eat, as well as our sleep quality. Activity levels, mood, motivation, hormones and medications also influence our energy levels.\n\nYou will benefit from the ongoing guidance and support of your certified personal coach who will help you increase your energy using a structured healthy eating and exercise program.\n\nThat being said, if your energy levels continue to fall you should consult your medical doctor."
  }
, "activity": {
	"notReady" : "Thanks for being honest about not being ready to become more physically active. This is a challenge for many people and you are not alone. Let us show you how small steps and activities from home can make a dramatic difference to your lifestyle.",
  	"motivated" : "We’re thrilled you are ready to embark on a more active lifestyle! Increased physical activity will help you lose weight, increase your energy, improve your mood, and reduce your risk for diseases like diabetes, heart disease, and cancer. We are going to work together to rediscover activities that you used to enjoy. We will also be sharing tips on how to increase your daily movement, and organizing Newtopia Activity Challenges designed to make physical activity fun and practical.",
  	"active" : "We’re thrilled you are ready to embark on a structured exercise routine! Increased regular physical activity will help you lose weight, increase your energy, improve your mood, and reduce your risk for diseases like diabetes, heart disease, and cancer. Together we will develop a structured cardio and strength program that works for you. You will also be invited to participate in fun Newtopia Activity Challenges."
  }
};
